# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "raq"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Caleb Buxton"]
  s.date = "2013-07-05"
  s.description = "The elegance of Rack with none of the unreliability of HTTP"
  s.email = "me@cpb.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".simplecov",
    ".travis.yml",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "features/README.md.feature",
    "features/raq.feature",
    "features/step_definitions/raq_steps.rb",
    "features/support/env.rb",
    "features/support/hooks.rb",
    "lib/raq.rb",
    "lib/raq/runner.rb",
    "lib/raq/server.rb",
    "lib/raq/server/builder.rb",
    "raq.gemspec",
    "spec/raq/runner_spec.rb",
    "spec/raq/server_spec.rb",
    "spec/raq_spec.rb",
    "spec/spec_helper.rb",
    "tmp/.gitkeep",
    "tmp/consumer.rb",
    "tmp/producer.rb",
    "tmp/rack_hack.rb"
  ]
  s.homepage = "http://github.com/cpb/raq"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Middleware for your AMQP Message Consumer"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, ["~> 1.0"])
      s.add_runtime_dependency(%q<amqp>, ["~> 1.0"])
      s.add_development_dependency(%q<bcat>, ["~> 0.6.2"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_development_dependency(%q<guard>, ["~> 1.8.0"])
      s.add_development_dependency(%q<guard-cucumber>, ["~> 1.4.0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 3.0.2"])
      s.add_development_dependency(%q<pry>, ["~> 0.9.12"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.0.0"])
      s.add_development_dependency(%q<rdiscount>, ["~> 2.1.6"])
      s.add_development_dependency(%q<travis-lint>, ["~> 1.7.0"])
    else
      s.add_dependency(%q<eventmachine>, ["~> 1.0"])
      s.add_dependency(%q<amqp>, ["~> 1.0"])
      s.add_dependency(%q<bcat>, ["~> 0.6.2"])
      s.add_dependency(%q<bundler>, ["~> 1.3.0"])
      s.add_dependency(%q<guard>, ["~> 1.8.0"])
      s.add_dependency(%q<guard-cucumber>, ["~> 1.4.0"])
      s.add_dependency(%q<guard-rspec>, ["~> 3.0.2"])
      s.add_dependency(%q<pry>, ["~> 0.9.12"])
      s.add_dependency(%q<rdoc>, ["~> 4.0.0"])
      s.add_dependency(%q<rdiscount>, ["~> 2.1.6"])
      s.add_dependency(%q<travis-lint>, ["~> 1.7.0"])
    end
  else
    s.add_dependency(%q<eventmachine>, ["~> 1.0"])
    s.add_dependency(%q<amqp>, ["~> 1.0"])
    s.add_dependency(%q<bcat>, ["~> 0.6.2"])
    s.add_dependency(%q<bundler>, ["~> 1.3.0"])
    s.add_dependency(%q<guard>, ["~> 1.8.0"])
    s.add_dependency(%q<guard-cucumber>, ["~> 1.4.0"])
    s.add_dependency(%q<guard-rspec>, ["~> 3.0.2"])
    s.add_dependency(%q<pry>, ["~> 0.9.12"])
    s.add_dependency(%q<rdoc>, ["~> 4.0.0"])
    s.add_dependency(%q<rdiscount>, ["~> 2.1.6"])
    s.add_dependency(%q<travis-lint>, ["~> 1.7.0"])
  end
end

